/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // LearnPath AI design system colors (from Stitch)
        "surface":                  "#0b1326",
        "surface-dim":              "#0b1326",
        "surface-container":        "#171f33",
        "surface-container-low":    "#131b2e",
        "surface-container-high":   "#222a3d",
        "surface-container-highest":"#2d3449",
        "surface-container-lowest": "#060e20",
        "surface-variant":          "#2d3449",
        "surface-bright":           "#31394d",
        "background":               "#0b1326",
        "on-surface":               "#dae2fd",
        "on-surface-variant":       "#c7c4d7",
        "on-background":            "#dae2fd",
        // Primary (violet/indigo)
        "primary":                  "#c0c1ff",
        "primary-fixed":            "#e1e0ff",
        "primary-fixed-dim":        "#c0c1ff",
        "primary-container":        "#8083ff",
        "on-primary":               "#1000a9",
        "on-primary-container":     "#0d0096",
        "on-primary-fixed":         "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary":          "#494bd6",
        // Secondary (cyan)
        "secondary":                "#4cd7f6",
        "secondary-container":      "#03b5d3",
        "secondary-fixed":          "#acedff",
        "secondary-fixed-dim":      "#4cd7f6",
        "on-secondary":             "#003640",
        "on-secondary-container":   "#00424e",
        "on-secondary-fixed":       "#001f26",
        "on-secondary-fixed-variant":"#004e5c",
        // Tertiary (purple)
        "tertiary":                 "#ddb7ff",
        "tertiary-container":       "#b76dff",
        "tertiary-fixed":           "#f0dbff",
        "tertiary-fixed-dim":       "#ddb7ff",
        "on-tertiary":              "#490080",
        "on-tertiary-container":    "#400071",
        "on-tertiary-fixed":        "#2c0051",
        "on-tertiary-fixed-variant":"#6900b3",
        // UI
        "outline":                  "#908fa0",
        "outline-variant":          "#464554",
        "surface-tint":             "#c0c1ff",
        "inverse-surface":          "#dae2fd",
        "inverse-on-surface":       "#283044",
        // Error
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
      },
      fontFamily: {
        sans:         ["Inter", "system-ui", "sans-serif"],
        display:      ["Hanken Grotesk", "Space Grotesk", "sans-serif"],
        mono:         ["JetBrains Mono", "monospace"],
        "body-lg":    ["Inter"],
        "body-md":    ["Inter"],
        "body-sm":    ["Inter"],
        "headline-lg":["Hanken Grotesk"],
        "headline-md":["Hanken Grotesk"],
        "label-md":   ["JetBrains Mono"],
      },
      fontSize: {
        "body-sm":    ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md":    ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg":    ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md":["30px", { lineHeight: "38px", fontWeight: "500" }],
        "headline-lg":["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md":   ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      spacing: {
        "unit-xs":         "4px",
        "unit-sm":         "8px",
        "unit-md":         "16px",
        "unit-lg":         "32px",
        "unit-xl":         "64px",
        "gutter":          "24px",
        "margin-mobile":   "16px",
        "sidebar-width":   "280px",
        "container-max":   "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
      animation: {
        "pulse-border":  "pulse-border 3s ease-in-out infinite",
        "float":         "float 4s ease-in-out infinite",
        "glow-pulse":    "glow-pulse 2.5s ease-in-out infinite",
        "scan-line":     "scan-line 3s linear infinite",
      },
      keyframes: {
        "pulse-border": {
          "0%, 100%": { borderColor: "rgba(192, 193, 255, 0.15)" },
          "50%":       { borderColor: "rgba(221, 183, 255, 0.50)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%":      { transform: "translateY(-6px)" },
        },
        "glow-pulse": {
          "0%, 100%": { opacity: "0.5" },
          "50%":      { opacity: "1" },
        },
        "scan-line": {
          "0%":   { top: "-2px" },
          "100%": { top: "100%" },
        },
      },
      backdropBlur: {
        xs: "2px",
      },
      boxShadow: {
        "glow-violet": "0 0 30px rgba(192, 193, 255, 0.15)",
        "glow-cyan":   "0 0 30px rgba(76, 215, 246, 0.15)",
        "glow-fuchsia":"0 0 30px rgba(217, 70, 239, 0.15)",
      },
    },
  },
  plugins: [],
};