package com.learnpath.analytics.service;

import com.learnpath.analytics.entity.AnalyticsRecommendation;
import com.learnpath.analytics.entity.AnalyticsSnapshot;
import com.learnpath.analytics.entity.LearningStreak;
import com.learnpath.analytics.repository.AnalyticsRecommendationRepository;
import com.learnpath.analytics.repository.AnalyticsSnapshotRepository;
import com.learnpath.analytics.repository.LearningStreakRepository;
import com.learnpath.mentor.repository.MentorProfileRepository;
import com.learnpath.placement.entity.PlacementProfile;
import com.learnpath.placement.entity.PlacementReadiness;
import com.learnpath.placement.repository.PlacementProfileRepository;
import com.learnpath.placement.repository.PlacementReadinessRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
public class AnalyticsRecommendationGenerator {

    private static final Logger log = LoggerFactory.getLogger(AnalyticsRecommendationGenerator.class);

    private final AnalyticsRecommendationRepository recommendationRepository;
    private final AnalyticsSnapshotRepository snapshotRepository;
    private final LearningStreakRepository streakRepository;
    private final MentorProfileRepository mentorProfileRepository;
    private final PlacementProfileRepository placementProfileRepository;
    private final PlacementReadinessRepository placementReadinessRepository;

    public AnalyticsRecommendationGenerator(
            AnalyticsRecommendationRepository recommendationRepository,
            AnalyticsSnapshotRepository snapshotRepository,
            LearningStreakRepository streakRepository,
            MentorProfileRepository mentorProfileRepository,
            PlacementProfileRepository placementProfileRepository,
            PlacementReadinessRepository placementReadinessRepository) {
        this.recommendationRepository = recommendationRepository;
        this.snapshotRepository = snapshotRepository;
        this.streakRepository = streakRepository;
        this.mentorProfileRepository = mentorProfileRepository;
        this.placementProfileRepository = placementProfileRepository;
        this.placementReadinessRepository = placementReadinessRepository;
    }

    @Transactional
    public List<AnalyticsRecommendation> generateRecommendations(UUID userId) {
        log.info("Generating recommendations for user: {}", userId);
        Optional<AnalyticsSnapshot> latestOpt = snapshotRepository.findFirstByUserIdOrderBySnapshotTimeDesc(userId);
        if (latestOpt.isEmpty()) {
            return List.of();
        }
        AnalyticsSnapshot latest = latestOpt.get();

        List<AnalyticsRecommendation> recommendations = new ArrayList<>();

        // 1. Roadmap Continuation
        if (latest.getRoadmapCompletion().compareTo(new BigDecimal("100.00")) < 0) {
            addRecommendation(recommendations, userId, "ROADMAP_CONTINUATION", "Continue Learning Roadmap",
                    "Progress through your assigned roadmap nodes to acquire target skills.", "/api/v1/roadmaps");
        }

        // 2. Assessment Retake
        if (latest.getAssessmentAverage().compareTo(new BigDecimal("60.00")) < 0) {
            addRecommendation(recommendations, userId, "ASSESSMENT_RETAKE", "Retake Assessment Modules",
                    "Your average assessment score is below 60%. Retaking assessments will help reinforce learning.", "/api/v1/assessments/templates");
        }

        // 3. Streak Maintenance
        Optional<LearningStreak> streakOpt = streakRepository.findByUserId(userId);
        if (streakOpt.isPresent() && streakOpt.get().getCurrentStreak() > 0) {
            addRecommendation(recommendations, userId, "STREAK_MAINTENANCE", "Maintain Learning Streak",
                    "Keep up the momentum! Complete one lesson or quiz today to maintain your streak.", "/api/v1/courses");
        }

        // 4. Complete Mentor Suggestions
        if (mentorProfileRepository.existsByUserId(userId)) {
            addRecommendation(recommendations, userId, "MENTOR_SUGGESTIONS", "Complete Mentor Suggestions",
                    "Review recommendations generated by your AI mentor.", "/api/v1/mentor/recommendations");
        }

        // 5. Placement Readiness Gaps
        List<PlacementProfile> profiles = placementProfileRepository.findByUserId(userId);
        if (!profiles.isEmpty()) {
            for (PlacementProfile profile : profiles) {
                Optional<PlacementReadiness> readinessOpt = placementReadinessRepository.findFirstByProfileIdOrderByCreatedAtDesc(profile.getId());
                if (readinessOpt.isPresent()) {
                    PlacementReadiness r = readinessOpt.get();
                    if (r.getAptitudeScore().compareTo(new BigDecimal("70.00")) < 0) {
                        addRecommendation(recommendations, userId, "APTITUDE_PRACTICE", "Practice Aptitude Questions",
                                "Your aptitude score is below target. Complete mock aptitude modules.", "/api/v1/assessments/templates");
                    }
                    if (r.getCommunicationScore().compareTo(new BigDecimal("70.00")) < 0) {
                        addRecommendation(recommendations, userId, "COMMUNICATION_IMPROVEMENT", "Improve Communication Skills",
                                "Your communication readiness is low. Practice peer mock interviews.", "/api/v1/placements/preferences");
                    }
                    if (r.getTechnicalScore().compareTo(new BigDecimal("70.00")) < 0) {
                        addRecommendation(recommendations, userId, "TECHNICAL_STRENGTHENING", "Strengthen Technical Skills",
                                "Focus on core engineering competencies to boost your technical readiness score.", "/api/v1/roadmaps");
                    }
                }
            }
        }

        return recommendationRepository.saveAll(recommendations);
    }

    private void addRecommendation(List<AnalyticsRecommendation> list, UUID userId, String type, String title, String desc, String url) {
        if (!recommendationRepository.existsByUserIdAndRecommendationTypeAndTitleAndCompletedFalse(userId, type, title)) {
            list.add(new AnalyticsRecommendation(userId, type, title, desc, url));
        }
    }
}
